# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """
[░▒▓](#a3aed2)\
$time\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
$git_state\
[](fg:#394260 bg:#212736)\
$nodejs\
$rust\
$golang\
$gradle\
$python\
$terraform\
$package\
[](fg:#212736 bg:#1d2230)\
$kubernetes\
$gcloud\
$os$username\
[ ](fg:#1d2230)\
$cmd_duration\
\n$character"""

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#a3aed2 fg:#090c0c"
format = '[  $time ]($style)'


[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "fg:#769ff0 bg:#394260"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:#769ff0 bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[git_state]
style = "fg:#769ff0 bg:#394260"
format = '\([$state ($progress_current/$progress_total)]($style)\)'

[nodejs]
symbol = ""
style = "fg:#769ff0 bg:#212736"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "fg:#769ff0 bg:#212736"
format = '[ $symbol ($version)]($style)'

[golang]
symbol = ""
style = "fg:#769ff0 bg:#212736"
format = '[ $symbol ($version) ]($style)'

[gradle]
symbol = ""
style = "fg:#769ff0 bg:#212736"
format = '[ $symbol ($version) ]($style)'
recursive = true

[python]
symbol = ""
style = "fg:#769ff0 bg:#212736"
format = '[ $symbol ($version) ]($style)'

[terraform]
symbol = "󱁢"
style = "fg:#769ff0 bg:#212736"
format = '[ $symbol ($version$workspace) ]($style)'

[package]
symbol = "󰏖"
style = "fg:#769ff0 bg:#212736"
format = '[ $symbol ($version) ]($style)'

[kubernetes]
disabled = false
style = "fg:#a0a9cb bg:#1d2230"
symbol = "󱃾"
format = '[ $symbol $context(\($namespace\))]($style)'

[gcloud]
disabled = false
style = "fg:#a0a9cb bg:#1d2230"
symbol = ""
format = '[ $symbol ($project)\($region\)]($style)'

[os]
style = "fg:#a0a9cb bg:#1d2230"
disabled = false

[os.symbols]
Debian = "  "
Ubuntu = "  "
Gentoo = " 󰣨 "

[username]
style_user = "fg:#a0a9cb bg:#1d2230"
format = "[$user]($style)"

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
